name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ImageMagick and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick libmagickwand-dev pkg-config

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false

      - name: Install Bundler
        run: gem install bundler

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Verify ImageMagick installation
        run: pkg-config --cflags --libs MagickCore

      - name: Install latest Brakeman
        run: gem install brakeman

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: brakeman --no-pager


  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ImageMagick and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick libmagickwand-dev pkg-config

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false

      - name: Install Bundler
        run: gem install bundler

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Verify ImageMagick installation
        run: pkg-config --cflags --libs MagickCore

      - name: Lint code for consistent style
        run: bin/rubocop -f github


  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick libmagickwand-dev pkg-config google-chrome-stable curl libjemalloc2 libvips postgresql-client

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false

      - name: Install Bundler
        run: gem install bundler

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Verify ImageMagick installation
        run: pkg-config --cflags --libs MagickCore

      - name: Check db hostname resolution
        run: |
          ping -c 1 db || echo "db host is not reachable"

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            PGPASSWORD=postgres pg_isready -h db -U postgres && break
            echo "Waiting for db to be ready..."
            sleep 2
          done

      - name: Prepare database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml
          bin/rails db:create
          bin/rails db:migrate

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@db:5432/myapp_test
        run: bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
